language: java

env:
  global:
    - JABBA_HOME=/home/travis/.jabba

cache:
  directories:
    - $HOME/.m2

before_cache:
  - rm -rf $HOME/.m2/repository/com/github/java-native
  - rm -rf $HOME/.m2/repository/io/github/java-native

matrix:
  include:
    - os: linux
      dist: bionic
      arch: amd64
      env:
        - TRAVIS_JDK=adopt@1.11.0-1
      addons:
        apt:
          packages:
            - cmake
            - g++
    - os: linux
      dist: bionic
      arch: amd64
      env:
        - TRAVIS_JDK=adopt-openj9@1.11.0-5
      addons:
        apt:
          packages:
            - cmake
            - g++
    - os: linux
      dist: bionic
      arch: amd64
      env:
        - TRAVIS_JDK=openjdk@1.14.0-32
      addons:
        apt:
          packages:
            - cmake
            - g++

before_install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.0/install.sh | bash && . ~/.jabba/jabba.sh

install:
  - $JABBA_HOME/bin/jabba install $TRAVIS_JDK
  # this is blocked by MDEP-204. - ./mvnw dependency:go-offline

script: ./mvnw --batch-mode clean verify

after_success:
  - bash <(curl -s https://codecov.io/bash)


