name: Release New Version
on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: false

env:
  MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  JAVA_TOOL_OPTIONS: -Duser.name=io.github.java-native
  GITHUB_BOT_NAME: github-actions
  GITHUB_BOT_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com

jobs:
  maven-central-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "${GITHUB_BOT_EMAIL}"
      - run: git config --global user.name "${GITHUB_BOT_NAME}"
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          server-id: ossrh
          server-username: OSSRH_TOKEN_USERNAME
          server-password: OSSRH_TOKEN_PASSWORD
          gpg-private-key: ${{ secrets.JAVA_NATIVE_PGP_KEY }}
          gpg-passphrase: PGP_KEY_PASSPHRASE
      - name: Set release version if provided as input
        if: github.event.inputs.releaseVersion != ''
        run: echo "VERSIONS=-DreleaseVersion=${{ github.event.inputs.releaseVersion }}" >> $GITHUB_ENV
      - name: Publish artifacts to Maven Central
        run: mvn -B release:prepare release:perform -P package,maven-central-release ${VERSIONS}
        env:
          OSSRH_TOKEN_USERNAME: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          OSSRH_TOKEN_PASSWORD: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          PGP_KEY_PASSPHRASE: ${{ secrets.JAVA_NATIVE_PGP_KEY_PASSPHRASE }}
      - name: Push changes back to repo
        run: git push && git push --tags --force
